# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Doc/Vivado2019_1/ALINX_AXI_WITH_FIFO/ALINX_AXI_WITH_FIFO.srcs/sources_1/bd/design_1/ip/design_1_fifo_16_1024_0_0/design_1_fifo_16_1024_0_0.xci
# IP: The module: 'design_1_fifo_16_1024_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Doc/Vivado2019_1/ALINX_AXI_WITH_FIFO/ALINX_AXI_WITH_FIFO.srcs/sources_1/bd/design_1/ip/design_1_fifo_16_1024_0_0/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# XDC: d:/Doc/Vivado2019_1/ALINX_AXI_WITH_FIFO/ALINX_AXI_WITH_FIFO.srcs/sources_1/bd/design_1/ip/design_1_fifo_16_1024_0_0/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Doc/Vivado2019_1/ALINX_AXI_WITH_FIFO/ALINX_AXI_WITH_FIFO.srcs/sources_1/bd/design_1/ip/design_1_fifo_16_1024_0_0/sources_1/ip/fifo_generator_0/fifo_generator_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: D:/Doc/Vivado2019_1/ALINX_AXI_WITH_FIFO/ALINX_AXI_WITH_FIFO.srcs/sources_1/bd/design_1/ip/design_1_fifo_16_1024_0_0/design_1_fifo_16_1024_0_0.xci
# IP: The module: 'design_1_fifo_16_1024_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Doc/Vivado2019_1/ALINX_AXI_WITH_FIFO/ALINX_AXI_WITH_FIFO.srcs/sources_1/bd/design_1/ip/design_1_fifo_16_1024_0_0/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# XDC: d:/Doc/Vivado2019_1/ALINX_AXI_WITH_FIFO/ALINX_AXI_WITH_FIFO.srcs/sources_1/bd/design_1/ip/design_1_fifo_16_1024_0_0/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Doc/Vivado2019_1/ALINX_AXI_WITH_FIFO/ALINX_AXI_WITH_FIFO.srcs/sources_1/bd/design_1/ip/design_1_fifo_16_1024_0_0/sources_1/ip/fifo_generator_0/fifo_generator_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
